//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hedin.UI.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hedin.UI.Localization.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently in Devmode.
        /// </summary>
        public static string HUIAppBar_DevMode {
            get {
                return ResourceManager.GetString("HUIAppBar.DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch app.
        /// </summary>
        public static string HUIAppDrawer_SwitchService {
            get {
                return ResourceManager.GetString("HUIAppDrawer.SwitchService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application drawer.
        /// </summary>
        public static string HUIAppDrawer_Tooltip {
            get {
                return ResourceManager.GetString("HUIAppDrawer.Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached files.
        /// </summary>
        public static string HUIBlogPost_AttachedFiles {
            get {
                return ResourceManager.GetString("HUIBlogPost.AttachedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string HUIBlogPost_EditLink {
            get {
                return ResourceManager.GetString("HUIBlogPost.EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less.
        /// </summary>
        public static string HUIBlogPost_Less {
            get {
                return ResourceManager.GetString("HUIBlogPost.Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        public static string HUIBlogPost_More {
            get {
                return ResourceManager.GetString("HUIBlogPost.More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string HUIBlogPost_Show {
            get {
                return ResourceManager.GetString("HUIBlogPost.Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string HUICommon_Add {
            get {
                return ResourceManager.GetString("HUICommon.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string HUICommon_Back {
            get {
                return ResourceManager.GetString("HUICommon.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string HUICommon_Close {
            get {
                return ResourceManager.GetString("HUICommon.Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string HUICommon_Delete {
            get {
                return ResourceManager.GetString("HUICommon.Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string HUICommon_Edit {
            get {
                return ResourceManager.GetString("HUICommon.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string HUICommon_Send {
            get {
                return ResourceManager.GetString("HUICommon.Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage table settings.
        /// </summary>
        public static string HUIDataGrid_ManageTableSettings {
            get {
                return ResourceManager.GetString("HUIDataGrid.ManageTableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset column settings to default.
        /// </summary>
        public static string HUIDataGrid_ResetTableSettings {
            get {
                return ResourceManager.GetString("HUIDataGrid.ResetTableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table settings.
        /// </summary>
        public static string HUIDataGrid_TableSettings {
            get {
                return ResourceManager.GetString("HUIDataGrid.TableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string HUIDialogUnsavedChanges_ButtonTextCancel {
            get {
                return ResourceManager.GetString("HUIDialogUnsavedChanges.ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string HUIDialogUnsavedChanges_ButtonTextClose {
            get {
                return ResourceManager.GetString("HUIDialogUnsavedChanges.ButtonTextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes that will be lost.
        /// </summary>
        public static string HUIDialogUnsavedChanges_Text {
            get {
                return ResourceManager.GetString("HUIDialogUnsavedChanges.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close window.
        /// </summary>
        public static string HUIDialogUnsavedChanges_TitleText {
            get {
                return ResourceManager.GetString("HUIDialogUnsavedChanges.TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string HUIInfoMessage_EditLink {
            get {
                return ResourceManager.GetString("HUIInfoMessage.EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read this notification.
        /// </summary>
        public static string HUIInfoMessage_IHaveReadThisNotification {
            get {
                return ResourceManager.GetString("HUIInfoMessage.IHaveReadThisNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marked as read.
        /// </summary>
        public static string HUIInfoMessage_MarkedAsRead {
            get {
                return ResourceManager.GetString("HUIInfoMessage.MarkedAsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to archive.
        /// </summary>
        public static string HUIInfoMessage_MoveToArchive {
            get {
                return ResourceManager.GetString("HUIInfoMessage.MoveToArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage filter settings.
        /// </summary>
        public static string HUIPageFilter_ManageFilterButtonText {
            get {
                return ResourceManager.GetString("HUIPageFilter.ManageFilterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset filters.
        /// </summary>
        public static string HUIPageFilter_ResetFilters {
            get {
                return ResourceManager.GetString("HUIPageFilter.ResetFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string HUIPageFilter_SearchButtonText {
            get {
                return ResourceManager.GetString("HUIPageFilter.SearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download as Excel.
        /// </summary>
        public static string HUIPageTable_DownloadAsExcelButton {
            get {
                return ResourceManager.GetString("HUIPageTable.DownloadAsExcelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string HUIPageTable_QuickSearchLabel {
            get {
                return ResourceManager.GetString("HUIPageTable.QuickSearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search on all columns.
        /// </summary>
        public static string HUIPageTable_QuickSearchToolTip {
            get {
                return ResourceManager.GetString("HUIPageTable.QuickSearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the list.
        /// </summary>
        public static string HUIPageTable_Refresh {
            get {
                return ResourceManager.GetString("HUIPageTable.Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your commitment to our product.
        /// </summary>
        public static string HUISuggestionBox_FeedbackSent {
            get {
                return ResourceManager.GetString("HUISuggestionBox.FeedbackSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write suggestion or insights here.
        /// </summary>
        public static string HUISuggestionBox_Placeholder {
            get {
                return ResourceManager.GetString("HUISuggestionBox.Placeholder", resourceCulture);
            }
        }
    }
}
