name: Hedin UI Nuget

permissions:
  contents: read
  packages: write
  
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Build
        run: dotnet build --configuration Release src/Hedin.UI/
      - name: Pack
        run: dotnet pack --configuration Release --no-build  src/Hedin.UI/
      - name: Publish
        run: dotnet nuget push src/Hedin.UI/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_AUTH_TOKEN}} --skip-duplicate --timeout 600
