name: Hedin UI Template NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
          source-url: https://nuget.pkg.github.com/hedinbil/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.REPO_PAT }}

      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
        with:
          length: 7

      - name: Inject dynamic version into .nuspec
        run: |
          VERSION="1.0.0-${{ steps.short-sha.outputs.sha }}"
          sed -i "s|<version>.*</version>|<version>${VERSION}</version>|" Hedin.UI.Template.Server/Hedin.UI.Template.Server.nuspec

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Zip template into .nupkg
        run: |
          VERSION=$(xmllint --xpath "string(//version)" Hedin.UI.Template.Server/Hedin.UI.Template.Server.nuspec)
          mkdir package
          cp Hedin.UI.Template.Server/Hedin.UI.Template.Server.nuspec package/
          cp -r Hedin.UI.Template.Server/.template.config package/.template.config
          rsync -a --exclude bin --exclude obj --exclude .vs --exclude .template.config Hedin.UI.Template.Server/ package/
          cd package
          zip -r ../Hedin.UI.Template.Server.$VERSION.nupkg *
          cd ..

      - name: Push template package to GitHub NuGet feed
        run: |
          VERSION=$(xmllint --xpath "string(//version)" Hedin.UI.Template.Server/Hedin.UI.Template.Server.nuspec)
          dotnet nuget push Hedin.UI.Template.Server.$VERSION.nupkg --skip-duplicate
